### ISSUE TITLE
Auto Updating broken? 

### ISSUE THREAD

**Issue by MatthewBraun** [r-pufky/digikam#15]
Digikam 7.6.0 released Sat Mar 5, 2022 and the Dockerfile hasn't updated. 

"stable and latest containers are auto-rebuilt weekly." Is something wrong with the auto-rebuild ?

**Comment by r-pufky** [comment]
Latest 7.6.0 image is now up and should be available.

Automatic GPG verification of the digikam source was failing.

**Comment by r-pufky** [comment]
Yes, auto builds are failing because of gpg signature validation failures
(generally this happens because the keys cannot be retrieved from the
keyservers); alternatively, they fail because new dependencies are required
which need to be added.

I'll take a look this weekend when I have some free time and see
whats going on.

FYI, I've been focusing my free time getting the linuxserver digikam image
to equivalence for this image to transition the maintenance of digikam
docker to them.
