### ISSUE TITLE
New version has bug?

### ISSUE THREAD

**Issue by kotatrader** [r-pufky/digikam#3]
LibEGL issue solved on last version pulled recently, but still unable to run container...

Got this error:

Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
Digikam::DBinaryIface::checkDirForPath: Testing  "././/sbin/mysqld" ...
Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false

**Comment by r-pufky** [comment]
Thanks for the report.

The reason you are seeing "All Binaries Found : false" message, is because `mysql server` is **not** installed in this container. By default, digikam will look for all binaries, even if they are not used. This is safe to ignore -- external mysql connections will still work from the container.

> test-d_1  | Digikam::DBinaryIface::checkDirForPath: Testing  "mysqld" ...
> test-d_1  | Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
> test-d_1  | Digikam::DBinaryIface::checkDirForPath: Testing  "././/bin/mysql_install_db" ...
> test-d_1  | Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
> test-d_1  | Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
> test-d_1  | Digikam::DBinaryIface::checkDirForPath: Testing  "././/bin/mysqld" ...
> test-d_1  | Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
> test-d_1  | Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
> test-d_1  | Digikam::DBinaryIface::checkDirForPath: Testing  "././/sbin/mysql_install_db" ...
> test-d_1  | Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
> test-d_1  | Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false
> test-d_1  | Digikam::DBinaryIface::checkDirForPath: Testing  "././/sbin/mysqld" ...
> test-d_1  | Digikam::adjustedEnvironmentForAppImage: Adjusting environment variables for AppImage bundle
> test-d_1  | Digikam::DBinarySearch::slotAreBinariesFound: All Binaries Found :  false

---
In regards to still being unable to run the container, I need more information. After you see these messages, the binary should be running with the initial setup screens.

* If you are not using a reverse proxy, be *sure* to expose ports so you can connect (though this *is* insecure):

```
services:
  digikam:
    ...
    ports:
      - 5800:5800
```
Then connect to the container via: `http://{DOCKER HOST}:5800`

**Comment by kotatrader** [comment]
Thanks!

Exposing the ports did the trick!

Stay safe!

**Comment by r-pufky** [comment]
No worries. Have a good one!
