### ISSUE TITLE
Default password?

### ISSUE THREAD

**Issue by eisengrau** [r-pufky/digikam#4]
Hello,

I just tried your container (via HomelabOS), however I don't seem to know the default password for the web interface of Digikam? ...

![image](https://user-images.githubusercontent.com/42865787/82658585-88bd8200-9c27-11ea-8c1d-a5496d89110f.png)

If it is not specified/hardcoded, where should this be specified?

Thank you,

**Comment by r-pufky** [comment]
. I'm not familiar with HomelabOS; but it looks like in there custom setup that it is setting `VNC_PASSWORD` for use: https://gitlab.com/NickBusey/HomelabOS/-/blob/dev/roles/digikam/templates/docker-compose.digikam.yml.j2#L22 with a very old version of the release.

Setting `VNC_PASSWORD` environment option in the base container. See: https://github.com/jlesage/docker-baseimage-gui#vnc-password The prompt you are getting is set from the HomelabOS environment.

It looks like HomelabOS is running Digikam 6.1.0; current packages are 6.4.0 (stable) and 7.0.0-beta2 (latest)

I'm going to cut a CL against HomelabOS to migrate to the "stable" release. However, to fix your specific issue, It looks like there's an vault setting where you explicitly set your password.

**Comment by r-pufky** [comment]
Linking bug to HomelabOS: https://gitlab.com/NickBusey/HomelabOS/-/issues/483

**Comment by eisengrau** [comment]
Hello,

Awesome, thank you for looking through this! I decided the raise the issue here, as the documentation (or even a brief intro) of a specific service in HomelabOS is rather... spartan.

By the way, while we are here, I wanted to ask that all or some of the functions of Digikam can be used through the web interface? Asking because I haven't found a description of it on the official website, not even on others either. Not even a screenshot of it. The web interface is an optional featue of Digikabel instead? If this is or it is not the case, either way is a full blown X/VNC server required at all in the Docker container versus a web server/interface only?

**Comment by r-pufky** [comment]
> Awesome, thank you for looking through this! I decided the raise the issue here, as the documentation (or even a brief intro) of a specific service in HomelabOS is rather... spartan.

No worries.

> By the way, while we are here, I wanted to ask that all or some of the functions of Digikam can be used through the web interface? 

Yes. The docker image is built using the appimage, so all the existing plugins afe installed and should work through the container. There is potentially one issue with the global and geolocating the pictures on it, but that is due to how Google changed API access, not the image itself. This should be resolved upstream.

> Asking because I haven't found a description of it on the official website, not even on others either. Not even a screenshot of it. The web interface is an optional featue of Digikabel instead? 

Digikam is a full blown app for Osx, win, linux. So you can use it locally on your own machine. The docker image just provides a way for people to host it over a websocket, e.g. on their server with all their data.

> If this is or it is not the case, either way is a full blown X/VNC server required at all in the Docker container versus a web server/interface only?

Yes. The way the container works is that it runs the app in an x session, amd starts a local rdp/vnc session connected to it, which is forwarded over the websocket. If you would prefer not to do this, then you should install digikam locally on your machine and use it that way.

**Comment by r-pufky** [comment]
Going to resolve this bug. HomelabOS updated version to stable.

I didn't get an answer in terms of the VNC password being set in homelabOS, my working assumption is what I stated in the upstream bug (linked above) is correct. This is something that you'll have to ask in HomelabOS forums/chat/etc.
